### ISSUE TITLE
Learn Elm

### ISSUE THREAD

**Issue by nqthqn** [nqthqn/elmapps#1]
in Elm...

 - [x] The basics
 - [x] model, view, update
 - [x] HTML
 - [ ] Subscriptions and Commands
 - [ ] CSS
 - [ ] HTTP / Authentication
 - [ ] DOM Storage / indexedDB
 - [ ] Forms?

[try](http://elm-lang.org/try) & [share](https://runelm.io)

And continue to get curried away with elm:
 - 🎒 Read this [tutorial on SPAs](https://www.elm-tutorial.org/en/02-elm-arch/02-structure.html)
 - Listen to the complete [Elm Town podcast](https://elmtown.github.io/2016/09/23/editing-in-elm-town-episode-1.html) *on episode 1*
 - ✅ Finish reading [the guide](https://guide.elm-lang.org/architecture/user_input/forms.html)  _some chapters unavailable_
 - ✅ Play around with [side project](https://github.com/natsn/s1lascii)  
 - ✅ Read some [elm weekly](http://www.elmweekly.nl/)  
 - ✅ Finish watching ["Code is the Easy Part"](https://www.youtube.com/watch?v=DSjbTC-hvqQ) by Evan Czaplicki  
 - Watch yet another [intro to Elm](https://www.youtube.com/watch?v=zBHB9i8e3Kc)
 - [SVG tangrams](https://www.youtube.com/watch?v=eMxwECIC7mc) looks interesting
 - ✅ Read the [HTTP](https://guide.elm-lang.org/architecture/effects/http.html) part of the guide again. Try communicating with a different server.  
 - 🎒 Finish the ["Elm for Beginners Course"](http://courses.knowthen.com/courses/enrolled/elm-for-beginners) by James Moore **31% COMPLETE** 
 - Purchase the next course [here](http://courses.knowthen.com/p/elm-beyond-the-basics)
 - ✅ Do [exercise 1](https://github.com/knowthen/elm/tree/master/02%20more%20on%20functions) and continue.  _on ex. 4_
 - Read some more [awesome elm](https://github.com/isRuslan/awesome-elm#who-to-follow)
 - ✅ Read some [past tweets](https://twitter.com/elmlang)  
 - Listen to [Elm Town](https://elmtown.github.io/2016/12/01/The-Founding-Story-Ep-6.html)
 - Another good talk on [Elm in Production](https://www.youtube.com/watch?v=FV0DXNB94NE)
 - And [Effects as Data](https://www.youtube.com/watch?v=6EdXaWfoslc)
 - [web components in elm](https://www.youtube.com/watch?v=ar3TakwE8o0&index=3&list=PLwuxQEGOXhN5v6E-mzqujkWlq8ZY0dxCR)
 - Learn about the [debugger](https://pragmaticstudio.com/tutorials/elm-debugger) and check out this free code school. Looks interesting.

**Comment by natsn** [comment]
On refactoring...

> If you find yourself repeating yourself, maybe break things out. If a function gets too big, make a helper function. If you see related things, maybe move them to a module. But at the end of the day, it is not a huge deal if you let things get big. Elm is great at finding problems and making refactors easy... — The BDFL

**Comment by natsn** [comment]
💡 Make an app for gamified learning via the web. 

**Features**
 - Add links with notes easily.
 - Fun emojis for indicating progress. 
 - Show percents complete.
 - Easily pick up where you left off.
